USE master
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'KurProj2021')
DROP DATABASE KurProj2021
GO

DROP DATABASE SQL_Test

CREATE DATABASE KurProj2021
GO

USE KurProj2021
GO

CREATE TABLE Img
(
	ID INT NOT NULL IDENTITY(1,1),
	path NVARCHAR(100) NOT NULL,
	type INT NOT NULL,
	Place_ID INT NOT NULL,
)
GO

CREATE TABLE Review
(
	ID INT NOT NULL IDENTITY(1,1),
	Place_id INT NOT NULL,
	Auth_id INT NOT NULL,
	Comment TEXT,
	Public_date DATE,
)
GO

CREATE TABLE City
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
)
GO


CREATE TABLE Place
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	CityId INT NOT NULL,
	Address NVARCHAR NOT NULL,
	RATING NUMERIC(15,2),
	Description TEXT NULL,
)
GO


CREATE TABLE Userr
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Login NVARCHAR(20) NOT NULL,
	Password NVARCHAR(64) NOT NULL,
	Email NVARCHAR NOT NULL,
	Avatar NVARCHAR  NULL,
)
GO


ALTER TABLE USERR ADD
CONSTRAINT PK_User PRIMARY KEY (ID),
CONSTRAINT UK1_User UNIQUE (Login),
CONSTRAINT UK2_User UNIQUE (Email),
CONSTRAINT UK3_User UNIQUE (Avatar)
GO

ALTER TABLE City ADD
CONSTRAINT PK_City PRIMARY KEY (ID)
GO

ALTER TABLE Place ADD
CONSTRAINT PK_Place PRIMARY KEY (ID),
CONSTRAINT FK1_Place FOREIGN KEY (CityId) REFERENCES City (ID)
GO

ALTER TABLE Review ADD
CONSTRAINT PK_Review PRIMARY KEY (ID),
CONSTRAINT FK1_Review FOREIGN KEY (Place_id) REFERENCES Place (ID),
CONSTRAINT FK2_Review FOREIGN KEY (Auth_id) REFERENCES Userr (ID)
GO

ALTER TABLE Img ADD
CONSTRAINT PK_Img PRIMARY KEY (ID),
CONSTRAINT FK1_Img FOREIGN KEY (Place_id) REFERENCES Place (ID)
GO
